[package]
name = "stylesheet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
log = "0.4"
selectors = { git = "https://github.com/servo/servo/", rev = "a8deb4d" }
cssparser = "0.29.6"
notify = "5.0"
